Program Tabuada;
var N,R :integer;
Begin
	writeln ('                                  TABUADA                                       ');
	writeln;
	writeln('Por favor, digite um numero inteiro e positivo.');
	writeln;
	readln (N);
	writeln;
	R:=N*0;
	writeln ((N),(' x 0 = '),(R));
	writeln;
	R:=N*1;
	writeln ((N),(' x 1 = '),(R));
	writeln;
	R:=N*2;
	writeln ((N),(' x 2 = '),(R));
	writeln;
	R:=N*3;
	writeln ((N),(' x 3 = '),(R));
	writeln;
	R:=N*4;
	writeln ((N),(' x 4 = '),(R));
	writeln;
	R:=N*5;
	writeln ((N),(' x 5 = '),(R));
	writeln;
	R:=N*6;
	writeln ((N),(' x 6 = '),(R));
	writeln;
	R:=N*7;
	writeln ((N),(' x 7 = '),(R));
	writeln;
	R:=N*8;
	writeln ((N),(' x 8 = '),(R));
	writeln;
	R:=N*9;
	writeln ((N),(' x 9 = '),(R));
	writeln;
	R:=N*10;
	writeln ((N),(' x 10 = '),(R));
	readln;  
End.